spring:
  mongodb:
    embedded:
      version: 4.0.2
      features: ONLY_WITH_SSL, ONLY_64BIT, NO_HTTP_INTERFACE_ARG
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/test?authSource=admin
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - offline_access
            redirect-uri: http://localhost:8087/login/oauth2/code/auth0
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-1l0ixjw8yohsluoi.us.auth0.com/
            jwk-set-uri: https://dev-1l0ixjw8yohsluoi.us.auth0.com/.well-known/jwks.json
            authorization-uri: https://dev-1l0ixjw8yohsluoi.us.auth0.com/authorize
            token-uri: https://dev-1l0ixjw8yohsluoi.us.auth0.com/oauth/token
            user-info-uri: https://dev-1l0ixjw8yohsluoi.us.auth0.com/oauth/userinfo
      resourceserver:
        jwt:
          issuer-uri: https://dev-1l0ixjw8yohsluoi.us.auth0.com/
          audiences:
            - https://api.gaas.waterballsa.tw

frontend: http://localhost:3030

server:
  port: 8087

logging:
  level:
    org.springframework.security: trace

socketio:
  host: 127.0.0.1
  port: 9001
  active: ${SOCKET_IO_SERVER_START:false}

