spring:
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      port: 27017
      database: test
      username: root
      host: localhost
      authentication-database: admin
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-1l0ixjw8yohsluoi.us.auth0.com/

server:
  port: 8087
